// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpqsklebtgbeajboxhvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcXNrbGVidGdiZWFqYm94aHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzOTE2OTEsImV4cCI6MjA3Njk2NzY5MX0.M_H2LwvtbxmUeO5JTcfHBbRvdtl6FjFbdOO_3ALQR_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});